CREATE TABLE Users(
Id INT IDENTITY(1,1) PRIMARY KEY,
Firstname VARCHAR(30),
LastName VARCHAR(35),
Email VARCHAR(100),
Passwd VARCHAR(100)
)

CREATE TABLE Customers(
UserId INT IDENTITY(1,1) PRIMARY KEY,
CompanyName VARCHAR(200)
)

CREATE TABLE Rental(
Id INT IDENTITY(1,1) PRIMARY KEY,
CarId INT,
CustomerId INT,
RentDate DATETIME,
ReturnDate DATETIME

)